osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- xcodebuild clean build -project SwiftHash.xcodeproj -scheme SwiftHash-iOS -sdk iphonesimulator
- xcodebuild test -project SwiftHash.xcodeproj -scheme SwiftHash-iOS -sdk iphonesimulator
- xcodebuild clean build -project SwiftHash.xcodeproj -scheme SwiftHash-Mac -sdk macosx
- xcodebuild test -project SwiftHash.xcodeproj -scheme SwiftHash-Mac -sdk macosx
